[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/story/*"
  to = "/.netlify/functions/og/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
