// netlify/edge-functions/story.js
//
// Server-renders /story/:slug requests as full HTML pages so Googlebot,
// social crawlers, and humans all get real article content on first byte.
//
// Behavior:
//   GET /story/:slug -> 200 HTML with NewsArticle JSON-LD if slug exists
//   GET /story/:slug -> 302 redirect to / if slug doesn't exist (graceful)
//   GET /story/      -> 302 redirect to /
//
// Data source: /articles.json (generated by scripts/generate_sitemaps.py).
// Cached in module scope for 5 minutes; first request after a deploy pays
// the fetch cost (~100ms).

const SITE_URL = "https://theflightline.news";
const SITE_NAME = "The Flightline";
const PUBLISHER_LOGO = "https://theflightline.news/images/flightline-og-default.jpg";
const TAGLINE = "No Static. Just the Story.";
const CACHE_TTL_MS = 5 * 60 * 1000; // 5 minutes

// Module-scope cache. Persists across requests on the same edge instance.
let _cache = { data: null, fetchedAt: 0 };

const CAT_LABELS = {
  news: "News",
  govt: "Government",
  government: "Government",
  dev: "Development",
  development: "Development",
  opinion: "Opinion",
  events: "Events",
  military: "Military",
  education: "Education",
  sports: "Sports",
  community: "Community",
};

function escapeHtml(s) {
  if (s == null) return "";
  return String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function escapeJsonLd(s) {
  // For values inside <script type="application/ld+json">, JSON.stringify
  // handles the string escaping; we just need to defang </script>.
  if (s == null) return null;
  return String(s).replace(/<\/script/gi, "<\\/script");
}

function stripHtml(s) {
  if (!s) return "";
  return String(s).replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim();
}

async function loadArticles(origin) {
  const now = Date.now();
  if (_cache.data && (now - _cache.fetchedAt) < CACHE_TTL_MS) {
    return _cache.data;
  }
  const url = new URL("/articles.json", origin).toString();
  const resp = await fetch(url, { cache: "no-store" });
  if (!resp.ok) {
    // Don't poison the cache on failure; let next request retry.
    throw new Error(`articles.json fetch ${resp.status}`);
  }
  const data = await resp.json();
  _cache = { data, fetchedAt: now };
  return data;
}

function renderPage(article, canonicalUrl) {
  const headline = article.headline || SITE_NAME;
  const dek = article.dek || "";
  const byline = article.byline || `${SITE_NAME} Staff`;
  const date = article.date || "";
  const datePublished = article.datePublished || "";
  const cat = article.cat || "news";
  const catLabel = article.label || CAT_LABELS[cat] || "News";
  const body = article.body || "";
  const thumbnail = article.thumbnail || "";

  const absImage = thumbnail
    ? (thumbnail.startsWith("http") ? thumbnail : `${SITE_URL}${thumbnail}`)
    : PUBLISHER_LOGO;

  const metaDesc = (dek || stripHtml(body).slice(0, 200)).trim();
  const pageTitle = `${headline} | ${SITE_NAME}`;

  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "NewsArticle",
    "headline": headline,
    "description": metaDesc,
    "image": [absImage],
    "datePublished": datePublished,
    "dateModified": datePublished,
    "author": [{
      "@type": byline.toLowerCase().includes("staff") ? "Organization" : "Person",
      "name": byline,
    }],
    "publisher": {
      "@type": "NewsMediaOrganization",
      "name": SITE_NAME,
      "logo": {
        "@type": "ImageObject",
        "url": PUBLISHER_LOGO,
      },
    },
    "mainEntityOfPage": {
      "@type": "WebPage",
      "@id": canonicalUrl,
    },
    "articleSection": catLabel,
    "url": canonicalUrl,
  };

  const jsonLdStr = escapeJsonLd(JSON.stringify(jsonLd));

  // Fonts + site stylesheet pulled from production. The article body markup
  // already uses the .article-body class, .fl-statstrip, .fl-pullquote, etc.,
  // which all live in /assets/style.css.
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escapeHtml(pageTitle)}</title>
<meta name="description" content="${escapeHtml(metaDesc)}">
<link rel="canonical" href="${escapeHtml(canonicalUrl)}">

<!-- Open Graph -->
<meta property="og:type" content="article">
<meta property="og:site_name" content="${escapeHtml(SITE_NAME)}">
<meta property="og:title" content="${escapeHtml(headline)}">
<meta property="og:description" content="${escapeHtml(metaDesc)}">
<meta property="og:image" content="${escapeHtml(absImage)}">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta property="og:url" content="${escapeHtml(canonicalUrl)}">
<meta property="article:published_time" content="${escapeHtml(datePublished)}">
<meta property="article:section" content="${escapeHtml(catLabel)}">
<meta property="article:author" content="${escapeHtml(byline)}">

<!-- Twitter -->
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="${escapeHtml(headline)}">
<meta name="twitter:description" content="${escapeHtml(metaDesc)}">
<meta name="twitter:image" content="${escapeHtml(absImage)}">

<!-- Favicon -->
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">

<!-- Fonts + site CSS -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=DM+Sans:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet">
<link rel="stylesheet" href="/assets/style.css">

<style>
  /* Page-specific layout. Uses site CSS variables (--navy, --gold, --bd, etc.) */
  body { background: var(--bg); color: var(--ink); font-family: 'DM Sans', system-ui, sans-serif; }
  .ssr-shell-header { background: var(--navy); color: #fff; padding: 14px 0; border-bottom: 4px solid var(--gold); }
  .ssr-shell-header-inner { max-width: 1200px; margin: 0 auto; padding: 0 20px; display: flex; align-items: center; justify-content: space-between; gap: 20px; }
  .ssr-wordmark a { display: flex; align-items: baseline; gap: 10px; color: #fff; text-decoration: none; }
  .ssr-wordmark .ssr-wm-name { font-family: 'DM Sans', sans-serif; font-weight: 900; font-size: 22px; letter-spacing: 0.02em; text-transform: uppercase; }
  .ssr-wordmark .ssr-wm-tag { font-family: Georgia, serif; font-style: italic; font-size: 12px; color: var(--gold); }
  .ssr-shell-header nav a { color: rgba(255,255,255,0.85); font-family: 'DM Sans', sans-serif; font-size: 12px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.06em; text-decoration: none; margin-left: 18px; }
  .ssr-shell-header nav a:hover { color: var(--gold); }

  .ssr-article-wrap { max-width: 660px; margin: 0 auto; padding: 36px 20px 64px; }
  .ssr-cat-row { display: flex; align-items: center; gap: 12px; padding-bottom: 12px; border-bottom: 1px solid var(--bd); margin-bottom: 18px; }
  .ssr-cat-badge { font-family: 'DM Sans', sans-serif; font-size: 10px; font-weight: 800; letter-spacing: 0.12em; text-transform: uppercase; color: #fff; padding: 5px 10px; border-radius: 3px; background: var(--gold); }
  .ssr-cat-badge.cat-govt { background: var(--cat-govt); }
  .ssr-cat-badge.cat-government { background: var(--cat-govt); }
  .ssr-cat-badge.cat-dev { background: var(--cat-dev); }
  .ssr-cat-badge.cat-development { background: var(--cat-dev); }
  .ssr-cat-badge.cat-opinion { background: var(--cat-opinion); }
  .ssr-cat-badge.cat-events { background: var(--cat-events); }
  .ssr-cat-badge.cat-military { background: var(--cat-military); }
  .ssr-cat-badge.cat-education { background: var(--cat-education); }
  .ssr-cat-badge.cat-sports { background: var(--cat-sports); }
  .ssr-cat-badge.cat-community { background: var(--cat-news); }
  .ssr-cat-badge.cat-news { background: var(--cat-news); }

  h1.ssr-headline { font-family: 'DM Sans', sans-serif; font-weight: 900; font-size: 32px; line-height: 1.12; color: var(--navy); margin: 6px 0 14px; letter-spacing: -0.01em; }
  .ssr-dek { font-size: 18px; color: var(--g1); line-height: 1.55; margin-bottom: 14px; font-weight: 400; }
  .ssr-byline { font-family: 'DM Sans', sans-serif; font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.06em; color: var(--g2); margin-bottom: 26px; padding-bottom: 18px; border-bottom: 1px solid var(--bd); }
  .ssr-byline .ssr-byline-name { color: var(--gold); }

  .ssr-footer { background: var(--navy); color: rgba(255,255,255,0.7); padding: 28px 20px; margin-top: 48px; text-align: center; font-family: 'DM Sans', sans-serif; font-size: 12px; }
  .ssr-footer a { color: var(--gold); text-decoration: none; font-weight: 700; }
  .ssr-footer a:hover { color: #fff; }
  .ssr-footer .ssr-footer-tag { font-family: Georgia, serif; font-style: italic; font-size: 13px; color: rgba(255,255,255,0.55); margin-top: 6px; }

  @media (max-width: 720px) {
    h1.ssr-headline { font-size: 26px; }
    .ssr-dek { font-size: 16px; }
    .ssr-shell-header-inner { flex-wrap: wrap; gap: 10px; }
    .ssr-shell-header nav a { margin-left: 0; margin-right: 14px; }
  }
</style>

<script type="application/ld+json">${jsonLdStr}</script>
</head>
<body>

<header class="ssr-shell-header">
  <div class="ssr-shell-header-inner">
    <div class="ssr-wordmark">
      <a href="/">
        <span class="ssr-wm-name">${escapeHtml(SITE_NAME)}</span>
        <span class="ssr-wm-tag">${escapeHtml(TAGLINE)}</span>
      </a>
    </div>
    <nav>
      <a href="/">Home</a>
      <a href="/?p=about">About</a>
      <a href="/?p=tips">Send a Tip</a>
    </nav>
  </div>
</header>

<main class="ssr-article-wrap">
  <article>
    <div class="ssr-cat-row">
      <span class="ssr-cat-badge cat-${escapeHtml(cat)}">${escapeHtml(catLabel)}</span>
    </div>
    <h1 class="ssr-headline">${escapeHtml(headline)}</h1>
    ${dek ? `<p class="ssr-dek">${escapeHtml(dek)}</p>` : ""}
    <p class="ssr-byline">
      By <span class="ssr-byline-name">${escapeHtml(byline)}</span>${date ? ` · ${escapeHtml(date)}` : ""}
    </p>

    <div class="article-body">
      ${body}
    </div>
  </article>
</main>

<footer class="ssr-footer">
  <div><strong>${escapeHtml(SITE_NAME)}</strong> · <a href="/">Read more from The Flightline</a></div>
  <div class="ssr-footer-tag">${escapeHtml(TAGLINE)}</div>
</footer>

</body>
</html>`;
}


// User-agent detection. We render the SSR shell for crawlers (so they get full
// HTML + JSON-LD on first byte for SEO and link previews), and fall through to
// the SPA for humans (so they get the full Flightline article experience —
// nav, ticker, Flightline Brief, font controls, related stories, etc.).
//
// Conservative bot list: matches well-known indexers, social link previewers,
// and headless/automation UAs. Anything else is treated as a human and routed
// to the SPA via context.next().
const BOT_UA_PATTERN = /bot|crawler|spider|crawling|googlebot|bingbot|slurp|duckduckbot|baiduspider|yandexbot|sogou|exabot|facebot|facebookexternalhit|twitterbot|linkedinbot|slackbot|telegrambot|whatsapp|discordbot|pinterestbot|redditbot|applebot|petalbot|semrushbot|ahrefsbot|mj12bot|dotbot|chrome-lighthouse|headlesschrome|prerender|embedly|quora link preview|outbrain|tineye|gptbot|chatgpt-user|claudebot|claude-web|anthropic-ai|google-extended|perplexitybot|youbot|cohere-ai|bytespider/i;

function isBot(userAgent) {
  if (!userAgent) return false;
  return BOT_UA_PATTERN.test(userAgent);
}

export default async function handler(request, context) {
  const url = new URL(request.url);

  // Match /story/:slug exactly. Allow trailing slash. No nested paths.
  const m = url.pathname.match(/^\/story\/([^\/?#]+)\/?$/);
  if (!m) {
    // Bare /story/ or /story → send to homepage
    if (url.pathname === "/story" || url.pathname === "/story/") {
      return Response.redirect(new URL("/", url.origin).toString(), 302);
    }
    // Anything else under /story/ that doesn't match the pattern → SPA fallback
    return context.next();
  }

  const slug = decodeURIComponent(m[1]);

  // Humans → fall through to the SPA. The SPA's index.html loads, app.js boots,
  // routeFromUrl() reads the /story/:slug path and calls openArticle(slug),
  // and the user gets the full article experience (nav, ticker, Flightline
  // Brief, font controls, related stories). Crawlers below still get SSR.
  const ua = request.headers.get("user-agent") || "";
  if (!isBot(ua)) {
    return context.next();
  }

  let articlesData;
  try {
    articlesData = await loadArticles(url.origin);
  } catch (e) {
    // If we can't load articles.json, fall through to the SPA so the user
    // at least gets a working page.
    console.error("story.js: failed to load articles.json:", e.message);
    return context.next();
  }

  const article = articlesData.articles && articlesData.articles[slug];
  if (!article) {
    // Unknown slug → graceful redirect to homepage. Could be a 404 page later.
    return Response.redirect(new URL("/", url.origin).toString(), 302);
  }

  const canonicalUrl = `${SITE_URL}/story/${slug}`;
  const html = renderPage(article, canonicalUrl);

  return new Response(html, {
    status: 200,
    headers: {
      "content-type": "text/html; charset=utf-8",
      // Browsers + CDN caching. Articles update infrequently.
      "cache-control": "public, max-age=300, s-maxage=600, stale-while-revalidate=86400",
      "x-rendered-by": "story-edge",
    },
  });
}

export const config = {
  path: "/story/*",
};
